---
language: python
python: "2.7"

# The tests will be run in Docker containers, to verify compatibility with 
# various OSes.
sudo: required
services:
  - docker
env:
  - TEST_CASE=centos_7
  #- TEST_CASE=ubuntu_16.04

install:
  # Prep the Docker container that will be used.
  - ./.travis/docker_launch.sh

  # Install ansible.
  - pip install -r requirements.txt
  - ansible --version
  - mkdir .travis/roles
  - ln -s ./ .travis/roles/karlmdavis.rcm

script:
  # Basic role syntax check
  - ansible-playbook tests/test_${TEST_CASE}.yml -i tests/inventory --syntax-check

  # Run the Ansible test case.
  - ansible-playbook ./.travis/test_${TEST_CASE}.yml --inventory-file=./.travis/inventory

after_script:
  - docker stop $(docker ps -a -q)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
