---
language: python
python: "2.7"

# The tests will be run in Docker containers, to verify compatibility with 
# various OSes.
sudo: required
services:
  - docker
env:
  # CentOS is mostly used as a standin for RHEL 7.
  - PLATFORM=centos_7 TEST_CASE=no_internet
  - PLATFORM=ubuntu_16_04 TEST_CASE=default

addons:
  apt:
    packages:
      - sshpass

install:
  # Ensure that the Travis test user has an SSH key.
  - if [[ ! -f ~/.ssh/id_rsa.pub ]]; then ssh-keygen -t rsa -N '' -f /home/travis/.ssh/id_rsa; fi

  # Prep the Docker container that will be used.
  - ./.travis/docker_launch.sh

  # Install ansible.
  - pip install -r requirements.frozen.txt
  - ansible --version
  - mkdir .travis/roles
  - ln -s `pwd` .travis/roles/karlmdavis.rcm

script:
  # Ensure that Ansible runs from this directory.
  - cd .travis/

  # Basic role syntax check
  - ansible-playbook test_base.yml --inventory-file=inventory --syntax-check

  # Run the Ansible test case.
  - ansible-playbook test_base.yml --inventory-file=inventory

after_script:
  # For debugging: inspect the management environment.
  - pwd
  - ls -la ../
  - ls -la ./
  - ls -la ./roles/

  # For debugging: inspect the Docker container.
  - docker exec ansible_test_rcm.${PLATFORM} /usr/bin/ls -la /home/ansible_test/

  # Stop all Docker containers.
  - docker stop $(docker ps -a -q)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

