---

- name: Add RCM PPA
  apt_repository:
    repo: 'ppa:martin-frost/thoughtbot-rcm'
    update_cache: true
  become: true

- name: Install RCM
  apt:
    name: rcm
    update_cache: true
  become: true

- set_fact:
    rcup_bin: /usr/bin/rcup

- name: Install rsync
  apt:
    name: rsync
    update_cache: true
  become: true
