---

- name: Tap Homebrew Repository for Thoughtbot
  homebrew_tap:
    # Per <https://github.com/thoughtbot/rcm>, this is required for RCM on MacOS.
    name: thoughtbot/formulae

- name: Install RCM
  homebrew:
    name: rcm
    state: present

- set_fact:
    rcup_bin: /usr/local/bin/rcup
