---

- name: Add RCM PPA
  apt_repository:
    repo: 'ppa:martin-frost/thoughtbot-rcm'
    update_cache: true
  become: true

- name: Install RCM
  apt:
    name: rcm
    update_cache: true
  become: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version in ['16.04', '18.04']

- name: Set rcup Path for Ubuntu
  set_fact:
    rcup_bin: /usr/bin/rcup

- name: Install rsync
  apt:
    name: rsync
    update_cache: true
  become: true
