---

# Determine which installation and configuration mechanism to use.
- set_fact: rcm_tasks="{{ 'main_no_internet.yml' if rcm_install_mode == 'no_internet' else 'main_{0}.yml'.format(ansible_distribution) }}"
- include: "{{ rcm_tasks }}"

- include: clone_repo.yml
  with_items: "{{ rcm_repos }}"
  loop_control:
    loop_var: rcm_repo

- set_fact: rcup_args="-x README.md -x LICENSE {{ rcm_repos | map(attribute='dest') | map('regex_replace', '(.*)', '-d \\1') | join(' ') }}
- name: Run rcup to Deploy Dotfiles
  command: "/usr/bin/rcup {{ rcup_args }}"
  become: true
  become_user: "{{ rcm_user }}"

