---

- name: Get Local Temporary File for RCM Archive
  tempfile:
    state: file
    prefix: 'rcm-'
    suffix: '.tar.gz'
  register: tempfile_rcm_archive_local
  delegate_to: localhost

- name: Download RCM Archive Locally
  get_url:
    url: 'https://thoughtbot.github.io/rcm/dist/rcm-1.3.1.tar.gz'
    checksum: 'sha256:9c8f92dba63ab9cb8a6b3d0ccf7ed8edf3f0fb388b044584d74778145fae7f8f'
    dest: "{{ tempfile_rcm_archive_local.path }}"
  delegate_to: localhost

- name: Get Remote Temporary Directory for RCM Archive
  tempfile:
    state: directory
    prefix: 'rcm-'
    suffix: '.tar.gz'
  register: tempfile_rcm_archive_remote

- name: Extract RCM Archive Remotely
  unarchive:
    copy: true
    src: "{{ tempfile_rcm_archive_local.path }}"
    dest: "{{ tempfile_rcm_archive_remote.path }}"
    owner: "{{ rcm_user }}"
    group: "{{ rcm_user }}"
    mode: u=rwx,g=rwx,o=rx

- name: Install RCM for User
  shell: ./configure && make && make install --prefix="{{ ansible_env.HOME }}"
    chdir: "{{ tempfile_rcm_archive_remote.path }}"
  become: true
  become_user: "{{ rcm_user }}"

