---

# Determine which installation and configuration mechanism to use.
- set_fact: rcm_install_tasks="{{ 'install_no_internet.yml' if rcm_install_mode == 'no_internet' else 'install_{0}.yml'.format(ansible_distribution) }}"
- include_tasks: "{{ rcm_install_tasks }}"

- include_tasks: clone_repo.yml
  with_items: "{{ rcm_repos }}"
  loop_control:
    loop_var: rcm_repo

- set_fact: rcup_bin="{{ '/home/{0}/bin/rcup'.format(rcm_user) if rcm_install_mode == 'no_internet' else '/usr/bin/rcup' }}"
- set_fact: rcup_args="-x README.md -x LICENSE {{ '-f' if rcm_replace_existing_files == true else '' }}{{ rcm_repos | map(attribute='dest') | map('regex_replace', '(.*)', ' -d \\1') | join('') }}"
- debug:
    var: rcm_repos
- debug:
    var: rcup_bin
- debug:
    var: rcup_args
- name: Run rcup to Deploy Dotfiles
  command: "{{ rcup_bin }} {{ rcup_args }}"
  become: true
  become_user: "{{ rcm_user }}"

